inputs:
  githubToken:
    required: true
  scope:
    required: true

outputs:
  branch:
    description: The created branch
    value: ${{steps.content.outputs.branch}}

runs:
  using: composite
  steps:
  - name: Create content
    id: content
    shell: bash
    run: |
      DATE_STRING="$(date --utc '+%Y-%m-%d %H:%M:%S')"
      MESSAGE="${{inputs.scope}} $DATE_STRING $RANDOM"
      echo "message=$MESSAGE" | tee -a "$GITHUB_OUTPUT"

      TOKEN="${MESSAGE//:/-}"
      TOKEN="${TOKEN// /-}"
      echo "token=$TOKEN" | tee -a "$GITHUB_OUTPUT"

      BRANCH="test-$TOKEN"
      echo "branch=$BRANCH" | tee -a "$GITHUB_OUTPUT"
      git checkout -b "$BRANCH"

      mkdir -p triggers
      echo "$MESSAGE" > "triggers/$TOKEN"

  - name: Commit and Push
    uses: remal-github-actions/push-back@v1
    with:
      githubToken: ${{inputs.githubToken}}
      message: '${{steps.content.outputs.message}}'
