name: Test

on:
  push:
    paths:
    - '.github/workflows/test.yml'
    branches:
    - 'main'
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1

    - name: Create content
      id: content
      run: |
        DATE_STRING="$(date --utc '+%Y-%m-%d %H:%M:%S')"
        echo "message=$DATE_STRING" |& tee --append "$GITHUB_OUTPUT"

        TOKEN="${DATE_STRING//:/-}"
        TOKEN="${TOKEN// /-}"
        echo "token=$TOKEN" |& tee --append "$GITHUB_OUTPUT"

        BRANCH="test-$TOKEN"
        echo "branch=$BRANCH" |& tee --append "$GITHUB_OUTPUT"
        git checkout -b "$BRANCH"

        rm -rf pr-triggers/*
        mkdir -p pr-triggers
        echo "$DATE_STRING" > "pr-triggers/$TOKEN"

    - name: Commit and Push
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.GH_TOKEN}}
        message: '${{steps.content.outputs.message}}'

    - name: Create PR
      id: create-pr
      run: |
        GH_LOGFILE=$(mktemp)
        gh pr create --fill --head "${{steps.content.outputs.branch}}" |& tee "$GH_LOGFILE"

        RESULT="${PIPESTATUS[0]}"
        if [ "$RESULT" -ne 0 ]; then
          exit "$RESULT"
        fi

        PR_URL=$(cat "$GH_LOGFILE")
        echo "pr-url=$PR_URL" |& tee --append "$GITHUB_OUTPUT"

        sleep 2s

    - name: Merge PR
      run: |
        gh pr merge "${{steps.create-pr.outputs.pr-url}}" --squash --delete-branch
