on:
  pull_request: { }
  push:
    branches:
    - 'test-*'
    tags:
    - 'test-*'

defaults:
  run:
    shell: bash

jobs:
  test-action:
    name: ${{github.event_name}}
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - name: Dump github context
      env: { CONTEXT: "${{toJson(github)}}" }
      run: echo "$CONTEXT"

    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s

    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
    - run: sleep 6s
