name: Test

on:
  push:
    paths:
    - '.github/workflows/test.yml'
    branches:
    - 'main'
  workflow_dispatch: { }

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1

    - name: Test
      env:
        GH_TOKEN: ${{github.token}}
      run: |
        git config push.autoSetupRemote true
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        DATE_STRING="$(date --utc '+%Y-%m-%d %H:%M:%S')"

        DATE_STRING_SAFE="${DATE_STRING//:/-}"
        DATE_STRING_SAFE="${DATE_STRING_SAFE// /-}"

        git checkout -b "$DATE_STRING_SAFE"

        rm -rf pr-triggers/*
        mkdir -p pr-triggers
        echo "$DATE_STRING" > "pr-triggers/$DATE_STRING_SAFE"

        git add --all .
        git commit --message="$DATE_STRING"
        git push

        gh pr create --fill
