name: Test

on:
  push:
    paths:
    - '.github/workflows/**'
    branches:
    - 'main'
  workflow_dispatch: { }

concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}

jobs:
  test-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1

    - name: Create and push content
      uses: ./.github/workflows/actions/push-content
      with:
        githubToken: ${{env.GH_TOKEN}}

    - name: Create PR
      id: create-pr
      run: |
        GH_LOGFILE=$(mktemp)
        gh pr create --fill --head "${{steps.content.outputs.branch}}" |& tee "$GH_LOGFILE"

        RESULT="${PIPESTATUS[0]}"
        if [ "$RESULT" -ne 0 ]; then
          exit "$RESULT"
        fi

        PR_URL=$(cat "$GH_LOGFILE")
        echo "pr-url=$PR_URL" | tee -a "$GITHUB_OUTPUT"

    - name: Merge PR
      run: |
        gh pr merge "${{steps.create-pr.outputs.pr-url}}" --squash --delete-branch
