on:
  pull_request: { }
  push:
    branches:
    - 'test-*'
    tags:
    - 'test-*'

defaults:
  run:
    shell: bash

jobs:
  test-action:
    name: ${{github.event_name}}
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
    - run: sleep 5s
